{% set name = "iso-639" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc9cd4b880b898d774c47fe9775167404af8a85dd889d58f9008035109acce49

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - iso639

about:
  home: https://github.com/noumar/iso639
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE.txt
  summary: "Python library for ISO 639 standard"
  dev_url: https://github.com/noumar/iso639

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
